# Comparing Two Identity By State (IBS) Matrices

```{r echo=FALSE, eval=FALSE}
# This codelab assumes that the current working directory is where the Rmd file
# resides
setwd("/YOUR/PATH/TO//1000Genomes-BRCA1/ibs")
```

This script takes two file names `ibs_filename1` and `ibs_filename2` as input.
Each input file should contain an N^2 * 3 matrix, where N is the size of the
population and each row represents the IBS score for a pair of individuals.

```{r message=FALSE, comment=NA}
library(reshape2)
read_ibs <- function(ibs_filename) {
  ibs_data <- read.table(file=ibs_filename, stringsAsFactors=FALSE)
  colnames(ibs_data) <- c("sample1", "sample2", "ibs_score")
  return (ibs_data)
}
ibs_data1 <- read_ibs(ibs_filename1)
ibs_data2 <- read_ibs(ibs_filename2)
```

Compare the two IBS matrices and report the differences.

```{r message=FALSE, comment=NA}
merged_ibs <- merge(ibs_data1, ibs_data2, by = c(colnames(ibs_data1)[1:2]))
diff_ibs <- abs(merged_ibs$ibs_score.x - merged_ibs$ibs_score.y) < 1e-6
merged_diff_ibs <- cbind(merged_ibs, diff_ibs)
colnames(merged_diff_ibs) <- c(colnames(merged_diff_ibs)[1:4],
                               "almost_equal_ibs")
dim(merged_diff_ibs[merged_diff_ibs$almost_equal_ibs == FALSE,])
```

